config/routes.rb
Gallery::Application.routes.draw do
  match 'admin' => 'admin#index'

  resources :photo_sets do
    resources :photos
  end

  devise_for :users

  mount Resque::Server.new, :at => '/resque'

  match 'contact' => 'pages#contact'

  root :to => 'pages#welcome'

end

app/views/shared/_navbar.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      = link_to t('application.name'), root_path, :class => 'brand'

      = link_to '#', :class => 'btn btn-navbar', :'data-toggle' => 'collapse', :'data-target' => '.nav-collapse' do
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

      .nav-collapse
        - if user_signed_in? && current_user.admin?
          %ul.nav.user-actions.pull-right
            %li.divider-vertical
            %li.dropdown
              = link_to '#', :class => 'dropdown-toggle logged-in-user-toggle', :'data-toggle' => 'dropdown' do
                = image_tag current_user.avatar.tiny.url, :alt => current_user.email, :size => '20x20', :class => 'avatar'
                = current_user.email
                %b.caret
              %ul.dropdown-menu
                %li= link_to 'Settings', edit_user_registration_path
                %li.divider
                %li= link_to 'Log out', destroy_user_session_path, :method => :delete
        %ul.nav.pull-right
          %li= link_to 'The Gallery', photo_sets_path, :class => controller_name.match(/photo/) ? 'active' : nil
          %li= link_to 'Contact', contact_path, :class => action_name.match(/contact/) ? 'active' : nil