config/routes.rb
Gallery::Application.routes.draw do
  match 'admin' => 'admin#index'

  resources :photo_sets do
    resources :photos
  end

  devise_for :users

  mount Resque::Server.new, :at => '/resque'

  match 'contact' => 'pages#contact'

  root :to => 'pages#welcome'

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :photo_set

  validates :name, :presence => true
  validates :description, :presence => true
  validates :photo_set, :presence => true
  validates :image, :presence => true

  mount_uploader :image, PhotoUploader
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # NOTE: Nested in PhotoSet resource

  # GET /photo_set/1/photos/1
  # GET /photo_set/1/photos/1.json
  def show
    @photo_set = PhotoSet.find(params[:photo_set_id])
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photo_set/1/photos/new
  # GET /photo_set/1/photos/new.json
  def new
    @photo_set = PhotoSet.find(params[:photo_set_id])
    @photo = Photo.new(:photo_set_id => @photo_set.id)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photo_set/1/photos/1/edit
  def edit
    @photo_set = PhotoSet.find(params[:photo_set_id])
    @photo = Photo.find(params[:id])
  end

  # POST /photo_set/1/photos
  # POST /photo_set/1/photos.json
  def create
    @photo_set = PhotoSet.find(params[:photo_set_id])
    @photo = Photo.new(params[:photo].merge(:photo_set_id => @photo_set.id))

    respond_to do |format|
      if @photo.save
        format.html { redirect_to [@photo_set, @photo], notice: 'Photo was successfully created.' }
        format.json { render json: [@photo_set, @photo], status: :created, location: [@photo_set, @photo] }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photo_set/1/photos/1
  # PUT /photo_set/1/photos/1.json
  def update
    @photo_set = PhotoSet.find(params[:photo_set_id])
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to [@photo_set, @photo], notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photo_set/1/photos/1
  # DELETE /photo_set/1/photos/1.json
  def destroy
    @photo_set = PhotoSet.find(params[:photo_set_id])
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photo_set_url(@photo_set) }
      format.json { head :no_content }
    end
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.haml
= simple_form_for([@photo_set, @photo], :html => { :method => :put, :class => 'form-horizontal validate' }) do |f|
  = f.error_notification

  %fieldset
    = f.input :name, :required => true
    = f.input :description, :required => true, :as => :text, :input_html => { :maxlength => 255 }
    = f.input :image, :required => false, :as => :image_preview, :input_html => { :preview_version => :thumbnail }

  .form-actions
    = f.button :submit, :class => 'btn-primary btn-large'

app/views/photos/edit.html.haml
.container
  .content
    .row
      .span12= alert_message_for(flash)

    .page-header
      %h1
        Photo
        %small Edit

    %h2= @photo.name

    .row
      .span12
        = render 'form'

    .row
      .span12
        = link_to 'Show', photo_set_photo_path(@photo_set, @photo), :class => 'btn'
        = link_to 'Back', photo_set_photos_path(@photo_set)

app/views/photos/new.html.haml
.container
  .content
    .row
      .span12= alert_message_for(flash)

    .page-header
      %h1
        Photo
        %small= @photo_set.name

    %h2 Create a new Photo

    .row
      .span12
        = render 'form'

    .row
      .span12
        = link_to 'Back', photo_set_path(@photo_set)

app/views/photos/show.html.haml
.container
  .content
    .row
      .span12= alert_message_for(flash)

    .page-header
      %h1
        = @photo.name
        %small= @photo_set.name

    %h2= @photo.description

    .row
      .span12
        %p= image_tag(@photo.image.url, :alt => @photo.name, :class => 'thumbnail')

    .row
      .span12
        %p
          - if user_signed_in? && current_user.admin?
            = link_to 'Edit', edit_photo_set_photo_path(@photo_set, @photo), :class => 'btn btn-primary'
          = link_to 'Back', photo_set_path(@photo_set)

  %footer.footer
    %p
      All images and content copyright Sam Nicholls.
      Images may not be used without prior express written consent.