config/routes.rb
Gallery::Application.routes.draw do
  match 'admin' => 'admin#index'

  resources :photo_sets do
    resources :photos
  end

  devise_for :users

  mount Resque::Server.new, :at => '/resque'

  match 'contact' => 'pages#contact'

  root :to => 'pages#welcome'

end

app/models/photo_set.rb
class PhotoSet < ActiveRecord::Base
  has_many :photos

  validates :name, :presence => true
  validates :description, :presence => true
end

app/controllers/photo_sets_controller.rb
class PhotoSetsController < ApplicationController
  # GET /photo_sets
  # GET /photo_sets.json
  def index
    @photo_sets = PhotoSet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photo_sets }
    end
  end

  # GET /photo_sets/1
  # GET /photo_sets/1.json
  def show
    @photo_set = PhotoSet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo_set }
    end
  end

  # GET /photo_sets/new
  # GET /photo_sets/new.json
  def new
    @photo_set = PhotoSet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo_set }
    end
  end

  # GET /photo_sets/1/edit
  def edit
    @photo_set = PhotoSet.find(params[:id])
  end

  # POST /photo_sets
  # POST /photo_sets.json
  def create
    @photo_set = PhotoSet.new(params[:photo_set])

    respond_to do |format|
      if @photo_set.save
        format.html { redirect_to @photo_set, notice: 'Photo set was successfully created.' }
        format.json { render json: @photo_set, status: :created, location: @photo_set }
      else
        format.html { render action: "new" }
        format.json { render json: @photo_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photo_sets/1
  # PUT /photo_sets/1.json
  def update
    @photo_set = PhotoSet.find(params[:id])

    respond_to do |format|
      if @photo_set.update_attributes(params[:photo_set])
        format.html { redirect_to @photo_set, notice: 'Photo set was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photo_sets/1
  # DELETE /photo_sets/1.json
  def destroy
    @photo_set = PhotoSet.find(params[:id])
    @photo_set.destroy

    respond_to do |format|
      format.html { redirect_to photo_sets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/photo_sets_helper.rb
module PhotoSetsHelper
end

app/views/photo_sets/_form.html.haml
= simple_form_for(@photo_set, :html => { :method => :put, :class => 'form-horizontal validate' }) do |f|
  = f.error_notification

  %fieldset
    = f.input :name, :required => true
    = f.input :description, :required => true, :as => :text, :input_html => { :maxlength => 255 }

  .form-actions
    = f.button :submit, :class => 'btn-primary btn-large'

app/views/photo_sets/edit.html.haml
.container
  .content
    .row
      .span12= alert_message_for(flash)

    .page-header
      %h1
        Photo Set
        %small Edit

    %h2= @photo_set.name

    .row
      .span8
        = render 'form'
      .span4
        .well
          %h3 Photos in this Photo Set

          %table.table.table-bordered.table-striped.table-condensed
            %thead
              %tr
                %th Name
                %th Description
                %th Image
                %th
            %tbody
              - @photo_set.photos.each do |photo|
                %tr
                  %td= photo.name
                  %td= photo.description
                  %td= image_tag(photo.image.thumbnail.url)
                  %td
                    = link_to 'Show', photo_set_photo_path(@photo_set, photo)
                    = link_to 'Edit', edit_photo_set_photo_path(@photo_set, photo)
                    = link_to 'Destroy', photo_set_photo_path(@photo_set, photo), :confirm => 'Are you sure?', :method => :delete

          %p= link_to 'Add a Photo', new_photo_set_photo_path(@photo_set), :class => 'btn btn-mini'

    .row
      .span12
        = link_to 'Show', @photo_set, :class => 'btn'
        = link_to 'Back', photo_sets_path

app/views/photo_sets/index.html.haml
.container
  .content
    .row
      .span12= alert_message_for(flash)

    .page-header
      %h1
        Photo Sets
        %small Collections of Photos

    %h2 Choose a Photo Set

    .row
      .span12
        %table.table.table-bordered.table-striped
          %thead
            %tr
              %th Name
              - if user_signed_in? && current_user.admin?
                %th
          %tbody
            - @photo_sets.each do |photo_set|
              %tr
                %td= link_to photo_set.name, photo_set
                - if user_signed_in? && current_user.admin?
                  %td
                    = link_to 'Show', photo_set
                    = link_to 'Edit', edit_photo_set_path(photo_set)
                    = link_to 'Destroy', photo_set, :confirm => 'Are you sure?', :method => :delete

    .row
      .span12
        %p
          - if user_signed_in? && current_user.admin?
            = link_to 'New Photo Set', new_photo_set_path, :class => 'btn btn-primary'
          = link_to 'Back', root_path

app/views/photo_sets/new.html.haml
.container
  .content
    .row
      .span12= alert_message_for(flash)

    .page-header
      %h1
        Photo Set
        %small New

    %h2 Create a new Photo Set

    .row
      .span12
        = render 'form'

    .row
      .span12
        = link_to 'Back', photo_sets_path

app/views/photo_sets/show.html.haml
.container
  .content
    .row
      .span12= alert_message_for(flash)

    .page-header
      %h1
        = @photo_set.name
        %small Photo Set

    %h2= @photo_set.description

    .row
      .span12
        - if @photo_set.photos.blank?
          There are no Photos for this Photo Set yet.
        - else
          %ul.thumbnails
            - @photo_set.photos.each do |photo|
              %li.span3
                .thumbnail
                  = link_to image_tag(photo.image.thumbnail.url, :alt => photo.name), [@photo_set, photo], :class => 'with_image'
                  .caption
                    %h5= link_to photo.name, [@photo_set, photo]
                    %p= photo.description

    .row
      .span12
        %p
          - if user_signed_in? && current_user.admin?
            = link_to 'Edit', edit_photo_set_path(@photo_set), :class => 'btn btn-primary'
          = link_to 'Back', photo_sets_path